# Generated by Django 5.1.7 on 2025-03-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name_plural': 'TODOS'},
        ),
    ]
